const PROJECT_LAYOUT = [
    "Tournaments.Tech",
    "GenDoc",
    "Gadha",
    "Cut-It",
    "fs.smrth.dev",
    "Portfolio 4.0",
    "Github Activity API",
    "Hyper.js",
    "Tabroom API",
    "Holler",
    "Tic Tac Toe Live",
    "Orial",
    "Tournaments.Tech (mobile)",
    "PyPI Download API",
    "Portfolio 3.0",
    "Stake",
    "Carbon Back",
    "QuickCite",
    "Madlibz",
    "2048.py",
    "Wish",
    "CasEel",
    "Hyper Landing Page",
    "CodeSwipe",
]

export default PROJECT_LAYOUT